name: Backup Repository to Azure Blob Storage

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Archive repository
        run: tar -czvf repository-backup.tar.gz .

      - name: Upload to Azure Blob Storage
        env:
          AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
          AZURE_STORAGE_CONTAINER: ${{ secrets.AZURE_STORAGE_CONTAINER }}
        run: |
          az storage blob upload --container-name $AZURE_STORAGE_CONTAINER --file repository-backup.tar.gz --name repository-backup-$(date +'%Y-%m-%d_%H-%M-%S').tar.gz
        shell: bash
